# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 23:13
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Donadores', '0003_auto_20161128_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donadores',
            name='Donador_nombre',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Valor invalido', regex='^[a-zA-Z\\s]*$')]),
        ),
    ]
