# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-28 14:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pacientes', '0003_auto_20161125_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defunciones',
            name='Apoyo',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='seguimiento_apoyo',
            name='Donacion_monetaria',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8),
        ),
    ]
