# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-30 17:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pacientes', '0004_auto_20161128_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seguimiento_apoyo',
            name='Donacion_especie',
            field=models.TextField(blank=True),
        ),
    ]
