# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 23:13
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pacientes', '0005_auto_20161130_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defunciones',
            name='Recipiente_nombre',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Valor invalido', regex='^[a-zA-Z\\s]*$')]),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='Paciente_apellido',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Valor invalido', regex='^[a-zA-Z\\s]*$')]),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='Paciente_contacto',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Ingrese un numero de telefono valido', regex='^[0-9|\\-]*$')]),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='Paciente_nombre',
            field=models.CharField(max_length=40, validators=[django.core.validators.RegexValidator(message='Valor invalido', regex='^[a-zA-Z\\s]*$')]),
        ),
    ]
