# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-02 11:50
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Administradores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Admon_nombre', models.CharField(max_length=40, validators=[django.core.validators.RegexValidator(message='Valor invalido', regex='^[a-zA-Z\\s]*$')])),
                ('Admon_tel', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Ingrese un numero de telefono valido', regex='^[0-9|\\-]*$')])),
                ('Admon_correo', models.EmailField(max_length=254)),
                ('perfil', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('editar', 'Edicion de registros'), ('crear_admin', 'Crear administradores'), ('asig_permisos', 'Asignar permisos')),
            },
        ),
        migrations.CreateModel(
            name='Eventos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre_evento', models.CharField(max_length=30)),
                ('Fecha_evento', models.DateField()),
                ('Lugar_evento', models.CharField(max_length=100)),
                ('Hora_evento', models.CharField(max_length=30)),
                ('Descripcion_evento', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Minutas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titulo_reunion', models.CharField(max_length=40)),
                ('Asunto_reunion', models.CharField(max_length=60)),
                ('Numero_reunion', models.IntegerField()),
                ('Fecha_reunion', models.DateField()),
                ('Duracion_reunion', models.CharField(max_length=15)),
                ('Anotaciones_reunion', models.TextField(blank=True)),
                ('Total_donacionesmon', models.DecimalField(decimal_places=2, max_digits=8)),
                ('Valor_donacionesesp', models.DecimalField(decimal_places=2, max_digits=8)),
                ('Pacientes_beneficiados', models.IntegerField()),
                ('Observaciones', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Personal_nombre', models.CharField(max_length=40, validators=[django.core.validators.RegexValidator(message='Valor invalido', regex='^[a-zA-Z\\s]*$')])),
                ('Personal_apellidos', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Valor invalido', regex='^[a-zA-Z\\s]*$')])),
                ('Personal_funcion', models.CharField(max_length=60)),
                ('Personal_tel', models.CharField(max_length=15)),
                ('Personal_correo', models.EmailField(max_length=254)),
            ],
        ),
        migrations.AddField(
            model_name='minutas',
            name='Asistentes',
            field=models.ManyToManyField(to='Admon.Personal'),
        ),
        migrations.AddField(
            model_name='minutas',
            name='Asistentes_administradores',
            field=models.ManyToManyField(to='Admon.Administradores'),
        ),
        migrations.AddField(
            model_name='eventos',
            name='Personal_evento',
            field=models.ManyToManyField(to='Admon.Personal'),
        ),
    ]
